export interface CloudGame {
  id: string
  title: string
  slug: string
  genre: string
  category: 'topAAA' | 'freeToPlay' | 'indieGems' | 'newReleases'
  thumbnail: string
  backdrop: string
  logo?: string
  description: string
  longDescription: string
  trailer?: string
  screenshots: string[]
  badges: string[]
  playCost: number
  rating: number
  players: string
  releaseDate: string
  developer: string
  publisher: string
  features: string[]
  systemReqs: {
    cpu: string
    gpu: string
    ram: string
    storage: string
  }
}

export const mockCloudGames: CloudGame[] = [
  {
    id: '1',
    title: 'Cyberpunk 2077',
    slug: 'cyberpunk-2077',
    genre: 'Action RPG',
    category: 'topAAA',
    thumbnail: 'https://upload.wikimedia.org/wikipedia/vi/9/9f/Cyberpunk_2077_box_art.jpg',
    backdrop: 'https://upload.wikimedia.org/wikipedia/vi/9/9f/Cyberpunk_2077_box_art.jpg',
    description: 'An open-world action-adventure story set in Night City, a megalopolis obsessed with power, glamour and body modification.',
    longDescription: 'Cyberpunk 2077 is an open-world, action-adventure RPG set in the dark future of Night City — a dangerous megalopolis obsessed with power, glamour, and ceaseless body modification. Play as V, a mercenary outlaw going after a one-of-a-kind implant that is the key to immortality.',
    screenshots: [
      'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=1280&h=720&fit=crop',
      'https://images.unsplash.com/photo-1542751110-97427bbecf20?w=1280&h=720&fit=crop',
      'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=1280&h=720&fit=crop',
    ],
    badges: ['RTX On', 'Cloud Ready', '4K'],
    playCost: 120,
    rating: 4.8,
    players: '125K',
    releaseDate: '2020',
    developer: 'CD PROJEKT RED',
    publisher: 'CD PROJEKT RED',
    features: ['Single Player', 'RTX Ray Tracing', 'Controller Support', 'Ultrawide Support'],
    systemReqs: {
      cpu: 'Intel Core i7-6700',
      gpu: 'NVIDIA GeForce RTX 2060',
      ram: '16 GB',
      storage: '70 GB SSD',
    },
  },
  {
    id: '2',
    title: 'Black Myth: Wukong',
    slug: 'black-myth-wukong',
    genre: 'Action RPG',
    category: 'newReleases',
    thumbnail: 'https://assets-prd.ignimgs.com/2024/08/18/blackmyth-1723969364570.jpg',
    backdrop: 'https://assets-prd.ignimgs.com/2024/08/18/blackmyth-1723969364570.jpg',
    description: 'An action RPG rooted in Chinese mythology. The story is based on Journey to the West, one of the Four Great Classical Novels of Chinese literature.',
    longDescription: 'Black Myth: Wukong is an action RPG rooted in Chinese mythology. You shall set out as the Destined One to venture into the challenges and marvels ahead, to uncover the obscured truth beneath the veil of a glorious legend from the past.',
    screenshots: [
      'https://images.unsplash.com/photo-1579952363873-27f3bade9f55?w=1280&h=720&fit=crop',
      'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=1280&h=720&fit=crop',
      'https://images.unsplash.com/photo-1493106641515-6b5631de4bb9?w=1280&h=720&fit=crop',
    ],
    badges: ['New', 'RTX On', 'Trending'],
    playCost: 150,
    rating: 4.9,
    players: '98K',
    releaseDate: '2024',
    developer: 'Game Science',
    publisher: 'Game Science',
    features: ['Single Player', 'Unreal Engine 5', 'RTX Ray Tracing', 'Chinese Mythology'],
    systemReqs: {
      cpu: 'Intel Core i7-9700',
      gpu: 'NVIDIA GeForce RTX 3060',
      ram: '16 GB',
      storage: '130 GB SSD',
    },
  },
  {
    id: '3',
    title: 'Genshin Impact',
    slug: 'genshin-impact',
    genre: 'Action RPG',
    category: 'freeToPlay',
    thumbnail: 'https://image.api.playstation.com/vulcan/ap/rnd/202508/2602/30935168a0f21b6710dc2bd7bb37c23ed937fb9fa747d84c.png',
    backdrop: 'https://image.api.playstation.com/vulcan/ap/rnd/202508/2602/30935168a0f21b6710dc2bd7bb37c23ed937fb9fa747d84c.png',
    description: 'Step into Teyvat, a vast world teeming with life and flowing with elemental energy. Discover this enchanting open-world adventure game.',
    longDescription: 'Genshin Impact is an open-world action RPG that sees you exploring the fantasy world of Teyvat, home to seven distinct nations, each tied to a different element and ruled by a different god. Discover the truth about your lost sibling and the world around you.',
    screenshots: [
      'https://images.unsplash.com/photo-1593305841991-05c297ba4575?w=1280&h=720&fit=crop',
      'https://images.unsplash.com/photo-1614730321146-b6fa6a46bcb4?w=1280&h=720&fit=crop',
      'https://images.unsplash.com/photo-1605711285791-0219e80e43a3?w=1280&h=720&fit=crop',
    ],
    badges: ['Free to Play', 'Cloud Ready', 'Popular'],
    playCost: 0,
    rating: 4.7,
    players: '245K',
    releaseDate: '2020',
    developer: 'miHoYo',
    publisher: 'miHoYo',
    features: ['Free to Play', 'Cross-Platform', 'Multiplayer', 'Gacha System'],
    systemReqs: {
      cpu: 'Intel Core i5',
      gpu: 'NVIDIA GeForce GTX 1030',
      ram: '8 GB',
      storage: '50 GB',
    },
  },
  {
    id: '4',
    title: 'Elden Ring',
    slug: 'elden-ring',
    genre: 'Action RPG',
    category: 'topAAA',
    thumbnail: 'https://m.media-amazon.com/images/M/MV5BMWNlMDBiYzYtMWMyMC00Zjc5LTlhMjItMjRlMzBmYmVkOGM0XkEyXkFqcGc@._V1_QL75_UY281_CR4,0,190,281_.jpg',
    backdrop: 'https://m.media-amazon.com/images/M/MV5BMWNlMDBiYzYtMWMyMC00Zjc5LTlhMjItMjRlMzBmYmVkOGM0XkEyXkFqcGc@._V1_QL75_UY281_CR4,0,190,281_.jpg',
    description: 'A new fantasy action RPG. Rise, Tarnished, and be guided by grace to brandish the power of the Elden Ring and become an Elden Lord.',
    longDescription: 'THE NEW FANTASY ACTION RPG. Rise, Tarnished, and be guided by grace to brandish the power of the Elden Ring and become an Elden Lord in the Lands Between. A vast world where open fields with a variety of situations and huge dungeons with complex and three-dimensional designs are seamlessly connected.',
    screenshots: [
      'https://images.unsplash.com/photo-1614680376739-414d95ff43df?w=1280&h=720&fit=crop',
      'https://images.unsplash.com/photo-1560155823-aaaa0255e8e6?w=1280&h=720&fit=crop',
      'https://images.unsplash.com/photo-1547394765-185e1e68f34e?w=1280&h=720&fit=crop',
    ],
    badges: ['RTX On', 'Award Winner', 'Cloud Ready'],
    playCost: 140,
    rating: 4.9,
    players: '187K',
    releaseDate: '2022',
    developer: 'FromSoftware',
    publisher: 'Bandai Namco',
    features: ['Single Player', 'Multiplayer', 'Controller Support', 'Steam Deck Verified'],
    systemReqs: {
      cpu: 'Intel Core i7-8700K',
      gpu: 'NVIDIA GeForce RTX 3060',
      ram: '16 GB',
      storage: '60 GB',
    },
  },
  {
    id: '5',
    title: 'Red Dead Redemption 2',
    slug: 'red-dead-redemption-2',
    genre: 'Action Adventure',
    category: 'topAAA',
    thumbnail: 'https://upload.wikimedia.org/wikipedia/vi/4/44/Red_Dead_Redemption_II.jpg',
    backdrop: 'https://upload.wikimedia.org/wikipedia/vi/4/44/Red_Dead_Redemption_II.jpg',
    description: 'America, 1899. Arthur Morgan and the Van der Linde gang are outlaws on the run. With federal agents and the best bounty hunters in the nation massing on their heels.',
    longDescription: 'America, 1899. The end of the Wild West era has begun. After a robbery goes badly wrong in the western town of Blackwater, Arthur Morgan and the Van der Linde gang are forced to flee. With federal agents and the best bounty hunters in the nation massing on their heels, the gang must rob, steal and fight their way across the rugged heartland of America.',
    screenshots: [
      'https://images.unsplash.com/photo-1607853202273-797f1c22a38e?w=1280&h=720&fit=crop',
      'https://images.unsplash.com/photo-1519608487953-e999c86e7455?w=1280&h=720&fit=crop',
      'https://images.unsplash.com/photo-1464047736614-af63643285bf?w=1280&h=720&fit=crop',
    ],
    badges: ['RTX On', 'Cloud Ready', '4K'],
    playCost: 130,
    rating: 4.8,
    players: '156K',
    releaseDate: '2018',
    developer: 'Rockstar Games',
    publisher: 'Rockstar Games',
    features: ['Single Player', 'Multiplayer', 'HDR Support', 'Ultrawide Support'],
    systemReqs: {
      cpu: 'Intel Core i7-4770K',
      gpu: 'NVIDIA GeForce GTX 1060',
      ram: '12 GB',
      storage: '150 GB',
    },
  },
  {
    id: '6',
    title: 'Valorant',
    slug: 'valorant',
    genre: 'FPS',
    category: 'freeToPlay',
    thumbnail: 'https://upload.wikimedia.org/wikipedia/en/b/ba/Valorant_cover.jpg',
    backdrop: 'https://upload.wikimedia.org/wikipedia/en/b/ba/Valorant_cover.jpg',
    description: 'VALORANT is a free-to-play first-person tactical shooter featuring high-stakes competitive gameplay.',
    longDescription: 'Blend your style and experience on a global, competitive stage. You have 13 rounds to attack and defend your side using sharp gunplay and tactical abilities. With a variety of characters to choose from, there is a play style for everyone.',
    screenshots: [
      'https://images.unsplash.com/photo-1542751110-97427bbecf20?w=1280&h=720&fit=crop',
      'https://images.unsplash.com/photo-1552820728-8b83bb6b773f?w=1280&h=720&fit=crop',
      'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=1280&h=720&fit=crop',
    ],
    badges: ['Free to Play', 'Low Latency', 'Competitive'],
    playCost: 0,
    rating: 4.6,
    players: '312K',
    releaseDate: '2020',
    developer: 'Riot Games',
    publisher: 'Riot Games',
    features: ['Free to Play', 'Multiplayer', 'Competitive', 'Anti-Cheat'],
    systemReqs: {
      cpu: 'Intel Core i3-4150',
      gpu: 'NVIDIA GeForce GT 730',
      ram: '4 GB',
      storage: '30 GB',
    },
  },
  {
    id: '7',
    title: 'Hollow Knight',
    slug: 'hollow-knight',
    genre: 'Metroidvania',
    category: 'indieGems',
    thumbnail: 'https://upload.wikimedia.org/wikipedia/en/0/04/Hollow_Knight_first_cover_art.webp',
    backdrop: 'https://upload.wikimedia.org/wikipedia/en/0/04/Hollow_Knight_first_cover_art.webp',
    description: 'Forge your own path in Hollow Knight! An epic action adventure through a vast ruined kingdom of insects and heroes.',
    longDescription: 'Forge your own path in Hollow Knight! An epic action adventure through a vast ruined kingdom of insects and heroes. Explore twisting caverns, battle tainted creatures and befriend bizarre bugs, all in a classic, hand-drawn 2D style.',
    screenshots: [
      'https://images.unsplash.com/photo-1611162616305-c69b3fa7fbe0?w=1280&h=720&fit=crop',
      'https://images.unsplash.com/photo-1493106641515-6b5631de4bb9?w=1280&h=720&fit=crop',
      'https://images.unsplash.com/photo-1547394765-185e1e68f34e?w=1280&h=720&fit=crop',
    ],
    badges: ['Indie', 'Cloud Ready', 'Award Winner'],
    playCost: 60,
    rating: 4.9,
    players: '78K',
    releaseDate: '2017',
    developer: 'Team Cherry',
    publisher: 'Team Cherry',
    features: ['Single Player', 'Controller Support', 'Hand-drawn Art', 'Atmospheric'],
    systemReqs: {
      cpu: 'Intel Core 2 Duo E5200',
      gpu: 'NVIDIA GeForce 9800GTX',
      ram: '4 GB',
      storage: '9 GB',
    },
  },
  {
    id: '8',
    title: 'Apex Legends',
    slug: 'apex-legends',
    genre: 'Battle Royale',
    category: 'freeToPlay',
    thumbnail: 'https://upload.wikimedia.org/wikipedia/en/d/db/Apex_legends_cover.jpg',
    backdrop: 'https://upload.wikimedia.org/wikipedia/en/d/db/Apex_legends_cover.jpg',
    description: 'Conquer with character in Apex Legends, a free-to-play* hero shooter where legendary characters with powerful abilities team up to battle.',
    longDescription: 'Master an ever-growing roster of legendary characters with powerful abilities, and experience strategic squad play and innovative gameplay in the next evolution of Hero Shooter and Battle Royale.',
    screenshots: [
      'https://images.unsplash.com/photo-1511988617509-a57c8a288659?w=1280&h=720&fit=crop',
      'https://images.unsplash.com/photo-1552820728-8b83bb6b773f?w=1280&h=720&fit=crop',
      'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=1280&h=720&fit=crop',
    ],
    badges: ['Free to Play', 'Low Latency', 'Battle Royale'],
    playCost: 0,
    rating: 4.5,
    players: '289K',
    releaseDate: '2019',
    developer: 'Respawn Entertainment',
    publisher: 'Electronic Arts',
    features: ['Free to Play', 'Battle Royale', 'Squad-based', 'Seasonal Content'],
    systemReqs: {
      cpu: 'Intel Core i3-6300',
      gpu: 'NVIDIA GeForce GT 640',
      ram: '6 GB',
      storage: '56 GB',
    },
  },
  {
    id: '9',
    title: 'PUBG Mobile',
    slug: 'pubg-mobile',
    genre: 'Battle Royale',
    category: 'freeToPlay',
    thumbnail: 'https://m.media-amazon.com/images/M/MV5BODQzNzJjY2QtY2Y2YS00OWJmLTlkZWMtMmNmMmE2NTg1MjQzXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
    backdrop: 'https://m.media-amazon.com/images/M/MV5BODQzNzJjY2QtY2Y2YS00OWJmLTlkZWMtMmNmMmE2NTg1MjQzXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
    description: 'PUBG MOBILE is the FREE battle royale shooter that pits 100 players against each other in a struggle for survival.',
    longDescription: 'PUBG MOBILE is the original battle royale game on mobile and one of the best mobile shooting games. Join the fight, put on your gear, and play to win. Survive in epic 100-player battles in classic mode, payload mode, fast-paced 4v4 team deathmatch and zombie modes.',
    screenshots: [
      'https://images.unsplash.com/photo-1511988617509-a57c8a288659?w=1280&h=720&fit=crop',
      'https://images.unsplash.com/photo-1542751110-97427bbecf20?w=1280&h=720&fit=crop',
      'https://images.unsplash.com/photo-1614680376593-902f74cf0d41?w=1280&h=720&fit=crop',
    ],
    badges: ['Free to Play', 'Mobile Ready', 'Popular'],
    playCost: 0,
    rating: 4.5,
    players: '423K',
    releaseDate: '2018',
    developer: 'KRAFTON, Inc.',
    publisher: 'KRAFTON, Inc.',
    features: ['Free to Play', 'Battle Royale', 'Mobile Optimized', 'Cross-Platform'],
    systemReqs: {
      cpu: 'Intel Core i3-4340',
      gpu: 'NVIDIA GeForce GTX 660',
      ram: '6 GB',
      storage: '40 GB',
    },
  },
  {
    id: '10',
    title: 'Honkai: Star Rail',
    slug: 'honkai-star-rail',
    genre: 'RPG',
    category: 'newReleases',
    thumbnail: 'https://image.api.playstation.com/vulcan/ap/rnd/202308/1103/8c3ce3611a4bb187418bb5e24924a055ba33d3046a7aaacb.png',
    backdrop: 'https://image.api.playstation.com/vulcan/ap/rnd/202308/1103/8c3ce3611a4bb187418bb5e24924a055ba33d3046a7aaacb.png',
    description: 'Honkai: Star Rail is a new HoYoverse space fantasy RPG. Hop aboard the Astral Express and experience the galaxy\'s infinite wonders on this journey.',
    longDescription: 'Honkai: Star Rail is a space fantasy RPG with a turn-based combat system. Players will meet new companions across various worlds and maybe even run into some familiar faces. Overcome the struggles together caused by Stellaron and unravel the hidden truths behind it.',
    screenshots: [
      'https://images.unsplash.com/photo-1593305841991-05c297ba4575?w=1280&h=720&fit=crop',
      'https://images.unsplash.com/photo-1614730321146-b6fa6a46bcb4?w=1280&h=720&fit=crop',
      'https://images.unsplash.com/photo-1618761714954-0b8cd0026356?w=1280&h=720&fit=crop',
    ],
    badges: ['New', 'Free to Play', 'Trending'],
    playCost: 0,
    rating: 4.6,
    players: '178K',
    releaseDate: '2023',
    developer: 'miHoYo',
    publisher: 'miHoYo',
    features: ['Free to Play', 'Turn-Based Combat', 'Gacha System', 'Story-Rich'],
    systemReqs: {
      cpu: 'Intel Core i5',
      gpu: 'NVIDIA GeForce GTX 1060',
      ram: '8 GB',
      storage: '40 GB',
    },
  },
  {
    id: '11',
    title: 'League of Legends',
    slug: 'league-of-legends',
    genre: 'MOBA',
    category: 'freeToPlay',
    thumbnail: 'https://i.imgur.com/I9JF3mh.jpeg',
    backdrop: 'https://i.imgur.com/I9JF3mh.jpeg',
    description: 'League of Legends is a team-based strategy game where two teams of five powerful champions face off to destroy the other\'s base.',
    longDescription: 'Join forces with your friends and test your skills in League of Legends, a competitive, multiplayer Battle Arena. Choose your champion, perfect your strategy, and outplay opponents in intense 5v5 matches.',
    screenshots: [
      'https://images.unsplash.com/photo-1542751110-97427bbecf20?w=1280&h=720&fit=crop',
      'https://images.unsplash.com/photo-1511988617509-a57c8a288659?w=1280&h=720&fit=crop',
      'https://images.unsplash.com/photo-1614680376593-902f74cf0d41?w=1280&h=720&fit=crop',
    ],
    badges: ['Free to Play', 'Competitive', 'E-Sports'],
    playCost: 0,
    rating: 4.7,
    players: '512K',
    releaseDate: '2009',
    developer: 'Riot Games',
    publisher: 'Riot Games',
    features: ['Free to Play', 'MOBA', 'Competitive', 'Team-Based'],
    systemReqs: {
      cpu: 'Intel Core i3-530',
      gpu: 'NVIDIA GeForce 9600GT',
      ram: '4 GB',
      storage: '16 GB',
    },
  },
  {
    id: '12',
    title: 'Minecraft',
    slug: 'minecraft',
    genre: 'Sandbox',
    category: 'indieGems',
    thumbnail: 'https://upload.wikimedia.org/wikipedia/vi/4/48/%E1%BA%A2nh_b%C3%ACa_Minecraft.png',
    backdrop: 'https://upload.wikimedia.org/wikipedia/vi/4/48/%E1%BA%A2nh_b%C3%ACa_Minecraft.png',
    description: 'Minecraft is a game about placing blocks and going on adventures. Explore randomly generated worlds and build amazing things.',
    longDescription: 'Minecraft is a sandbox video game where players explore a blocky, procedurally generated 3D world with virtually infinite terrain. Players can discover and extract raw materials, craft tools and items, and build structures.',
    screenshots: [
      'https://images.unsplash.com/photo-1607799279861-4dd421887fb3?w=1280&h=720&fit=crop',
      'https://images.unsplash.com/photo-1611162616305-c69b3fa7fbe0?w=1280&h=720&fit=crop',
      'https://images.unsplash.com/photo-1618761714954-0b8cd0026356?w=1280&h=720&fit=crop',
    ],
    badges: ['Sandbox', 'Cloud Ready', 'Creative'],
    playCost: 80,
    rating: 4.8,
    players: '634K',
    releaseDate: '2011',
    developer: 'Mojang Studios',
    publisher: 'Xbox Game Studios',
    features: ['Sandbox', 'Multiplayer', 'Creative Mode', 'Survival Mode'],
    systemReqs: {
      cpu: 'Intel Core i3-3210',
      gpu: 'NVIDIA GeForce 400 Series',
      ram: '4 GB',
      storage: '4 GB',
    },
  },
  {
    id: '13',
    title: "Baldur's Gate 3",
    slug: 'baldurs-gate-3',
    genre: 'RPG',
    category: 'topAAA',
    thumbnail: 'https://image.api.playstation.com/vulcan/ap/rnd/202302/2321/ba706e54d68d10a0eb6ab7c36cdad9178c58b7fb7bb03d28.png',
    backdrop: 'https://image.api.playstation.com/vulcan/ap/rnd/202302/2321/ba706e54d68d10a0eb6ab7c36cdad9178c58b7fb7bb03d28.png',
    description: 'Gather your party and return to the Forgotten Realms in a tale of fellowship and betrayal, sacrifice and survival, and the lure of absolute power.',
    longDescription: 'Baldur\'s Gate 3 is a story-rich, party-based RPG set in the universe of Dungeons & Dragons, where your choices shape a tale of fellowship and betrayal, survival and sacrifice, and the lure of absolute power.',
    screenshots: [
      'https://images.unsplash.com/photo-1579952363873-27f3bade9f55?w=1280&h=720&fit=crop',
      'https://images.unsplash.com/photo-1614680376593-902f74cf0d41?w=1280&h=720&fit=crop',
      'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=1280&h=720&fit=crop',
    ],
    badges: ['Award Winner', 'RTX On', 'Story-Rich'],
    playCost: 160,
    rating: 4.9,
    players: '134K',
    releaseDate: '2023',
    developer: 'Larian Studios',
    publisher: 'Larian Studios',
    features: ['Single Player', 'Multiplayer', 'Turn-Based', 'Story-Rich'],
    systemReqs: {
      cpu: 'Intel Core i5-4690',
      gpu: 'NVIDIA GeForce GTX 970',
      ram: '8 GB',
      storage: '150 GB',
    },
  },
  {
    id: '14',
    title: 'The Witcher 3: Wild Hunt',
    slug: 'the-witcher-3',
    genre: 'RPG',
    category: 'topAAA',
    thumbnail: 'https://upload.wikimedia.org/wikipedia/vi/e/e2/Bia_TheWitcher3.jpg',
    backdrop: 'https://upload.wikimedia.org/wikipedia/vi/e/e2/Bia_TheWitcher3.jpg',
    description: 'As war rages on throughout the Northern Realms, you take on the greatest contract of your life — tracking down the Child of Prophecy.',
    longDescription: 'The Witcher 3: Wild Hunt is a story-driven, next-generation open world role-playing game set in a visually stunning fantasy universe full of meaningful choices and impactful consequences.',
    screenshots: [
      'https://images.unsplash.com/photo-1607853202273-797f1c22a38e?w=1280&h=720&fit=crop',
      'https://images.unsplash.com/photo-1579952363873-27f3bade9f55?w=1280&h=720&fit=crop',
      'https://images.unsplash.com/photo-1614680376593-902f74cf0d41?w=1280&h=720&fit=crop',
    ],
    badges: ['Award Winner', 'RTX On', 'Classic'],
    playCost: 100,
    rating: 4.9,
    players: '267K',
    releaseDate: '2015',
    developer: 'CD PROJEKT RED',
    publisher: 'CD PROJEKT RED',
    features: ['Single Player', 'Open World', 'Story-Rich', 'Choice-Driven'],
    systemReqs: {
      cpu: 'Intel Core i5-2500K',
      gpu: 'NVIDIA GeForce GTX 660',
      ram: '6 GB',
      storage: '50 GB',
    },
  },
  {
    id: '15',
    title: 'Forza Horizon 5',
    slug: 'forza-horizon-5',
    genre: 'Racing',
    category: 'topAAA',
    thumbnail: 'https://upload.wikimedia.org/wikipedia/en/8/86/Forza_Horizon_5_cover_art.jpg',
    backdrop: 'https://upload.wikimedia.org/wikipedia/en/8/86/Forza_Horizon_5_cover_art.jpg',
    description: 'Your Ultimate Horizon Adventure awaits! Explore the vibrant and ever-evolving open world landscapes of Mexico.',
    longDescription: 'Explore the vibrant and ever-evolving open world landscapes of Mexico with limitless, fun driving action in hundreds of the world\'s greatest cars. This is a Horizon Adventure like no other.',
    screenshots: [
      'https://images.unsplash.com/photo-1607799279861-4dd421887fb3?w=1280&h=720&fit=crop',
      'https://images.unsplash.com/photo-1511988617509-a57c8a288659?w=1280&h=720&fit=crop',
      'https://images.unsplash.com/photo-1614680376739-414d95ff43df?w=1280&h=720&fit=crop',
    ],
    badges: ['RTX On', 'Cloud Ready', '4K'],
    playCost: 120,
    rating: 4.8,
    players: '198K',
    releaseDate: '2021',
    developer: 'Playground Games',
    publisher: 'Xbox Game Studios',
    features: ['Single Player', 'Multiplayer', 'Open World', '4K Ultra HD'],
    systemReqs: {
      cpu: 'Intel Core i5-8400',
      gpu: 'NVIDIA GeForce GTX 1070',
      ram: '16 GB',
      storage: '110 GB',
    },
  },
  {
    id: '16',
    title: 'Lies of P',
    slug: 'lies-of-p',
    genre: 'Action RPG',
    category: 'indieGems',
    thumbnail: 'https://upload.wikimedia.org/wikipedia/en/d/de/Lies_of_p_cover_art.jpg',
    backdrop: 'https://upload.wikimedia.org/wikipedia/en/d/de/Lies_of_p_cover_art.jpg',
    description: 'Lies of P is a thrilling soulslike that takes the story of Pinocchio, turns it on its head, and sets it against the darkly elegant backdrop of the Belle Epoque.',
    longDescription: 'You are a puppet created by Geppetto who\'s caught in a web of lies with unimaginable monsters and untrustworthy figures standing between you and the events that have befallen the world of Lies of P.',
    screenshots: [
      'https://images.unsplash.com/photo-1611162616305-c69b3fa7fbe0?w=1280&h=720&fit=crop',
      'https://images.unsplash.com/photo-1614680376593-902f74cf0d41?w=1280&h=720&fit=crop',
      'https://images.unsplash.com/photo-1579952363873-27f3bade9f55?w=1280&h=720&fit=crop',
    ],
    badges: ['Indie', 'Soulslike', 'Story-Rich'],
    playCost: 110,
    rating: 4.7,
    players: '89K',
    releaseDate: '2023',
    developer: 'Neowiz',
    publisher: 'Neowiz',
    features: ['Single Player', 'Soulslike', 'Story-Rich', 'Controller Support'],
    systemReqs: {
      cpu: 'Intel Core i7-3770',
      gpu: 'NVIDIA GeForce GTX 1060',
      ram: '8 GB',
      storage: '50 GB',
    },
  },
  {
    id: '17',
    title: 'The Smurfs Dreams',
    slug: 'the-smurfs-dreams',
    genre: 'Platform Adventure',
    category: 'indieGems',
    thumbnail: 'https://cdn.xsolla.net/image-proxy/rs:fit:3840:0/f:webp/quality:100/storage/mall-bucket-prod/cms/Updated_Smurfs.webp@webp',
    backdrop: 'https://cdn.xsolla.net/image-proxy/rs:fit:3840:0/f:webp/quality:100/storage/mall-bucket-prod/cms/Updated_Smurfs.webp@webp',
    description: 'Join the Smurfs on a colorful 3D platforming adventure through the Cursed Land to save Smurfette from Gargamel.',
    longDescription: 'The Smurfs Dreams is a 3D platformer that offers a vibrant adventure full of action, exploration and puzzles. Embark on an exciting quest to rescue Smurfette from Gargamel\'s clutches and save the Smurf Village from mysterious purple plants.',
    screenshots: [
      'https://cdn.xsolla.net/image-proxy/rs:fit:3840:0/f:webp/quality:100/storage/mall-bucket-prod/cms/Updated_Smurfs.webp@webp',
      'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=1280&h=720&fit=crop',
      'https://images.unsplash.com/photo-1614680376593-902f74cf0d41?w=1280&h=720&fit=crop',
    ],
    badges: ['Family Friendly', 'Cloud Ready', '3D Platformer'],
    playCost: 90,
    rating: 4.3,
    players: '12K',
    releaseDate: '2024',
    developer: 'Ocellus Studio',
    publisher: 'Microids',
    features: ['Single Player', 'Family Friendly', 'Controller Support', 'Colorful Graphics'],
    systemReqs: {
      cpu: 'Intel Core i5-6400',
      gpu: 'NVIDIA GeForce GTX 960',
      ram: '8 GB',
      storage: '15 GB',
    },
  },
  {
    id: '18',
    title: 'The Talos Principle 2',
    slug: 'the-talos-principle-2',
    genre: 'Puzzle',
    category: 'topAAA',
    thumbnail: 'https://cdn.xsolla.net/image-proxy/rs:fit:3840:0/f:webp/quality:100/storage/mall-bucket-prod/cms/WAncFB_CQbMJHkDr3MIdK.webp@webp',
    backdrop: 'https://cdn.xsolla.net/image-proxy/rs:fit:3840:0/f:webp/quality:100/storage/mall-bucket-prod/cms/WAncFB_CQbMJHkDr3MIdK.webp@webp',
    description: 'A thought-provoking first-person puzzle experience that greatly expands on the first game\'s philosophical themes and stunning environments.',
    longDescription: 'The Talos Principle 2 is a philosophical first-person puzzle game from Croteam. Solve dozens of challenging puzzles, explore an interconnected world, and unravel a cosmic mystery that will challenge your perspective on humanity, technology, and the nature of existence itself.',
    screenshots: [
      'https://cdn.xsolla.net/image-proxy/rs:fit:3840:0/f:webp/quality:100/storage/mall-bucket-prod/cms/WAncFB_CQbMJHkDr3MIdK.webp@webp',
      'https://images.unsplash.com/photo-1614680376593-902f74cf0d41?w=1280&h=720&fit=crop',
      'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=1280&h=720&fit=crop',
    ],
    badges: ['Puzzle', 'Story-Rich', 'Philosophy'],
    playCost: 140,
    rating: 4.8,
    players: '45K',
    releaseDate: '2023',
    developer: 'Croteam',
    publisher: 'Devolver Digital',
    features: ['Single Player', 'First-Person', 'Puzzle', 'Philosophical'],
    systemReqs: {
      cpu: 'Intel Core i5-7600K',
      gpu: 'NVIDIA GeForce GTX 1060',
      ram: '8 GB',
      storage: '100 GB',
    },
  },
  {
    id: '19',
    title: 'Make Way',
    slug: 'make-way',
    genre: 'Party Racing',
    category: 'indieGems',
    thumbnail: 'https://cdn.xsolla.net/image-proxy/rs:fit:3840:0/f:webp/quality:100/storage/mall-bucket-prod/cms/TjGntgRb6T5oyV1KrmzC2.webp@webp',
    backdrop: 'https://cdn.xsolla.net/image-proxy/rs:fit:3840:0/f:webp/quality:100/storage/mall-bucket-prod/cms/TjGntgRb6T5oyV1KrmzC2.webp@webp',
    description: 'A chaotic physics-based party racing game where you ram opponents off the track and cause mayhem.',
    longDescription: 'Make Way is an explosive party racing game where ramming your opponents off the road isn\'t just allowed, it\'s encouraged! Race through wild tracks with physics-based destruction, power-ups, and non-stop chaos. Perfect for couch co-op or online multiplayer mayhem.',
    screenshots: [
      'https://cdn.xsolla.net/image-proxy/rs:fit:3840:0/f:webp/quality:100/storage/mall-bucket-prod/cms/TjGntgRb6T5oyV1KrmzC2.webp@webp',
      'https://images.unsplash.com/photo-1614680376593-902f74cf0d41?w=1280&h=720&fit=crop',
      'https://images.unsplash.com/photo-1511988617509-a57c8a288659?w=1280&h=720&fit=crop',
    ],
    badges: ['Multiplayer', 'Party Game', 'Physics'],
    playCost: 80,
    rating: 4.4,
    players: '28K',
    releaseDate: '2023',
    developer: 'Secret Mode',
    publisher: 'Secret Mode',
    features: ['Multiplayer', 'Party Game', 'Physics-Based', 'Controller Support'],
    systemReqs: {
      cpu: 'Intel Core i5-4670',
      gpu: 'NVIDIA GeForce GTX 960',
      ram: '8 GB',
      storage: '10 GB',
    },
  },
  {
    id: '20',
    title: 'Empire of the Ants',
    slug: 'empire-of-the-ants',
    genre: 'Strategy RTS',
    category: 'newReleases',
    thumbnail: 'https://cdn.xsolla.net/image-proxy/rs:fit:3840:0/f:webp/quality:100/storage/mall-bucket-prod/cms/nluEvIEgGpTnGNQSBhStK.webp@webp',
    backdrop: 'https://cdn.xsolla.net/image-proxy/rs:fit:3840:0/f:webp/quality:100/storage/mall-bucket-prod/cms/nluEvIEgGpTnGNQSBhStK.webp@webp',
    description: 'Command an ant colony in this photorealistic RTS where you must strategize, conquer, and survive in the miniature world of insects.',
    longDescription: 'Empire of the Ants is a photorealistic real-time strategy game based on Bernard Werber\'s bestselling novel. Lead your ant colony through a tiny world rendered in stunning detail. Build your empire, forge alliances, and engage in epic battles against rival colonies and predators.',
    screenshots: [
      'https://cdn.xsolla.net/image-proxy/rs:fit:3840:0/f:webp/quality:100/storage/mall-bucket-prod/cms/nluEvIEgGpTnGNQSBhStK.webp@webp',
      'https://images.unsplash.com/photo-1614680376593-902f74cf0d41?w=1280&h=720&fit=crop',
      'https://images.unsplash.com/photo-1579952363873-27f3bade9f55?w=1280&h=720&fit=crop',
    ],
    badges: ['New', 'RTS', 'Photorealistic'],
    playCost: 130,
    rating: 4.6,
    players: '34K',
    releaseDate: '2024',
    developer: 'Tower Five',
    publisher: 'Microids',
    features: ['Single Player', 'Strategy', 'RTS', 'Photorealistic Graphics'],
    systemReqs: {
      cpu: 'Intel Core i7-8700',
      gpu: 'NVIDIA GeForce RTX 2060',
      ram: '16 GB',
      storage: '40 GB',
    },
  },
  {
    id: '21',
    title: 'Moon Mystery',
    slug: 'moon-mystery',
    genre: 'Adventure Mystery',
    category: 'indieGems',
    thumbnail: 'https://cdn.xsolla.net/image-proxy/rs:fit:3840:0/f:webp/quality:100/storage/mall-bucket-prod/cms/oDgIcyCrXG81KsL9nGrjF.webp@webp',
    backdrop: 'https://cdn.xsolla.net/image-proxy/rs:fit:3840:0/f:webp/quality:100/storage/mall-bucket-prod/cms/oDgIcyCrXG81KsL9nGrjF.webp@webp',
    description: 'Uncover the secrets of a lunar research facility in this narrative-driven mystery adventure set on the Moon.',
    longDescription: 'Moon Mystery is a first-person cosmic horror adventure set in a lunar research facility. Explore the abandoned station, solve environmental puzzles, and piece together what happened to the crew. Atmospheric storytelling meets scientific realism in this space thriller.',
    screenshots: [
      'https://cdn.xsolla.net/image-proxy/rs:fit:3840:0/f:webp/quality:100/storage/mall-bucket-prod/cms/oDgIcyCrXG81KsL9nGrjF.webp@webp',
      'https://images.unsplash.com/photo-1614680376593-902f74cf0d41?w=1280&h=720&fit=crop',
      'https://images.unsplash.com/photo-1611162616305-c69b3fa7fbe0?w=1280&h=720&fit=crop',
    ],
    badges: ['Mystery', 'Story-Rich', 'Space'],
    playCost: 95,
    rating: 4.5,
    players: '19K',
    releaseDate: '2024',
    developer: 'Cosmoscouts',
    publisher: 'Freedom Games',
    features: ['Single Player', 'Story-Rich', 'Mystery', 'Atmospheric'],
    systemReqs: {
      cpu: 'Intel Core i5-6600',
      gpu: 'NVIDIA GeForce GTX 1050 Ti',
      ram: '8 GB',
      storage: '25 GB',
    },
  },
  {
    id: '22',
    title: 'Raji: An Ancient Epic',
    slug: 'raji-an-ancient-epic',
    genre: 'Action Adventure',
    category: 'indieGems',
    thumbnail: 'https://cdn.xsolla.net/image-proxy/rs:fit:3840:0/f:webp/quality:100/storage/mall-bucket-prod/cms/G4tDZKnz4BbUEwmHniqOt.webp@webp',
    backdrop: 'https://cdn.xsolla.net/image-proxy/rs:fit:3840:0/f:webp/quality:100/storage/mall-bucket-prod/cms/G4tDZKnz4BbUEwmHniqOt.webp@webp',
    description: 'An action-adventure game set in ancient India where a young girl chosen by the gods must rescue her brother from demons.',
    longDescription: 'Raji: An Ancient Epic is an action-adventure game set in ancient India. A young girl named Raji has been chosen by the gods to stand against a demonic invasion. Armed with powerful weapons and abilities bestowed by the gods, embark on a journey to save your brother and restore balance.',
    screenshots: [
      'https://cdn.xsolla.net/image-proxy/rs:fit:3840:0/f:webp/quality:100/storage/mall-bucket-prod/cms/G4tDZKnz4BbUEwmHniqOt.webp@webp',
      'https://images.unsplash.com/photo-1579952363873-27f3bade9f55?w=1280&h=720&fit=crop',
      'https://images.unsplash.com/photo-1614680376593-902f74cf0d41?w=1280&h=720&fit=crop',
    ],
    badges: ['Indie', 'Action', 'Mythology'],
    playCost: 70,
    rating: 4.6,
    players: '42K',
    releaseDate: '2020',
    developer: 'Nodding Heads Games',
    publisher: 'Super.com',
    features: ['Single Player', 'Action', 'Indian Mythology', 'Beautiful Art Style'],
    systemReqs: {
      cpu: 'Intel Core i5-4460',
      gpu: 'NVIDIA GeForce GTX 760',
      ram: '6 GB',
      storage: '12 GB',
    },
  },
  {
    id: '23',
    title: 'GRIP: Combat Racing',
    slug: 'grip-combat-racing',
    genre: 'Combat Racing',
    category: 'freeToPlay',
    thumbnail: 'https://cdn.xsolla.net/image-proxy/rs:fit:3840:0/f:webp/quality:100/storage/mall-bucket-prod/cms/UIDYLUpI4A_xfIH_o-jVp.webp@webp',
    backdrop: 'https://cdn.xsolla.net/image-proxy/rs:fit:3840:0/f:webp/quality:100/storage/mall-bucket-prod/cms/UIDYLUpI4A_xfIH_o-jVp.webp@webp',
    description: 'High-octane futuristic combat racing inspired by classics like Rollcage. Race on ceilings, walls, and loop-de-loops at extreme speeds.',
    longDescription: 'GRIP: Combat Racing is a spiritual successor to the Rollcage games from the PS1 era. Race at breakneck speeds on tracks that twist, turn, and flip in every direction. Deploy devastating weapons, master gravity-defying vehicles, and dominate the competition in this adrenaline-fueled combat racer.',
    screenshots: [
      'https://cdn.xsolla.net/image-proxy/rs:fit:3840:0/f:webp/quality:100/storage/mall-bucket-prod/cms/UIDYLUpI4A_xfIH_o-jVp.webp@webp',
      'https://images.unsplash.com/photo-1511988617509-a57c8a288659?w=1280&h=720&fit=crop',
      'https://images.unsplash.com/photo-1614680376593-902f74cf0d41?w=1280&h=720&fit=crop',
    ],
    badges: ['Free to Play', 'Racing', 'Multiplayer'],
    playCost: 0,
    rating: 4.3,
    players: '67K',
    releaseDate: '2018',
    developer: 'Caged Element',
    publisher: 'Wired Productions',
    features: ['Free to Play', 'Multiplayer', 'Combat Racing', 'High Speed'],
    systemReqs: {
      cpu: 'Intel Core i5-4590',
      gpu: 'NVIDIA GeForce GTX 970',
      ram: '8 GB',
      storage: '16 GB',
    },
  },
  {
    id: '24',
    title: 'Who Wants to be a Millionaire?',
    slug: 'who-wants-to-be-a-millionaire',
    genre: 'Trivia Quiz',
    category: 'freeToPlay',
    thumbnail: 'https://cdn.xsolla.net/image-proxy/rs:fit:3840:0/f:webp/quality:100/storage/mall-bucket-prod/cms/-mIbNZDvX7Ke-i1zOIDxw.webp@webp',
    backdrop: 'https://cdn.xsolla.net/image-proxy/rs:fit:3840:0/f:webp/quality:100/storage/mall-bucket-prod/cms/-mIbNZDvX7Ke-i1zOIDxw.webp@webp',
    description: 'The official game based on the hit TV show. Answer trivia questions, use lifelines, and win virtual millions!',
    longDescription: 'Who Wants to be a Millionaire? brings the excitement of the iconic TV quiz show to your screen. Test your knowledge across various categories, strategically use your lifelines, and climb the money ladder. Perfect for solo play or competing with friends and family.',
    screenshots: [
      'https://cdn.xsolla.net/image-proxy/rs:fit:3840:0/f:webp/quality:100/storage/mall-bucket-prod/cms/-mIbNZDvX7Ke-i1zOIDxw.webp@webp',
      'https://images.unsplash.com/photo-1614680376593-902f74cf0d41?w=1280&h=720&fit=crop',
      'https://images.unsplash.com/photo-1511988617509-a57c8a288659?w=1280&h=720&fit=crop',
    ],
    badges: ['Free to Play', 'Trivia', 'Family Friendly'],
    playCost: 0,
    rating: 4.2,
    players: '89K',
    releaseDate: '2022',
    developer: 'Appeal Studios',
    publisher: 'Microids',
    features: ['Free to Play', 'Trivia', 'Multiplayer', 'Family Friendly'],
    systemReqs: {
      cpu: 'Intel Core i3-4160',
      gpu: 'NVIDIA GeForce GTX 660',
      ram: '4 GB',
      storage: '8 GB',
    },
  },
  {
    id: '25',
    title: 'Terra Nil',
    slug: 'terra-nil',
    genre: 'Strategy Puzzle',
    category: 'indieGems',
    thumbnail: 'https://cdn.xsolla.net/image-proxy/rs:fit:3840:0/f:webp/quality:100/storage/mall-bucket-prod/cms/SHRlWtG6DcJiq-RyJRzdm.webp@webp',
    backdrop: 'https://cdn.xsolla.net/image-proxy/rs:fit:3840:0/f:webp/quality:100/storage/mall-bucket-prod/cms/SHRlWtG6DcJiq-RyJRzdm.webp@webp',
    description: 'A reverse city-builder about ecosystem reconstruction. Transform a barren wasteland into an ecological paradise.',
    longDescription: 'Terra Nil is an intricate environmental strategy game about transforming a barren wasteland into a thriving, balanced ecosystem. Bring life back to a lifeless world by purifying soil, cleaning oceans, planting trees, and reintroducing wildlife. A meditative, reverse city-builder focused on restoration.',
    screenshots: [
      'https://cdn.xsolla.net/image-proxy/rs:fit:3840:0/f:webp/quality:100/storage/mall-bucket-prod/cms/SHRlWtG6DcJiq-RyJRzdm.webp@webp',
      'https://images.unsplash.com/photo-1611162616305-c69b3fa7fbe0?w=1280&h=720&fit=crop',
      'https://images.unsplash.com/photo-1614680376593-902f74cf0d41?w=1280&h=720&fit=crop',
    ],
    badges: ['Indie', 'Relaxing', 'Eco'],
    playCost: 85,
    rating: 4.7,
    players: '56K',
    releaseDate: '2023',
    developer: 'Free Lives',
    publisher: 'Devolver Digital',
    features: ['Single Player', 'Strategy', 'Relaxing', 'Environmental'],
    systemReqs: {
      cpu: 'Intel Core i5-3570',
      gpu: 'NVIDIA GeForce GTX 660',
      ram: '4 GB',
      storage: '2 GB',
    },
  },
]

export function getGameBySlug(slug: string): CloudGame | undefined {
  return mockCloudGames.find(game => game.slug === slug)
}

export function getGamesByCategory(category: string): CloudGame[] {
  if (category === 'all') return mockCloudGames
  return mockCloudGames.filter(game => game.category === category)
}
